sudo: required
services:
    - docker:

before_install:
    - docker build -t yashchauhan/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true yashchauhan/docker-react npm run test

deploy:
  edge: true
  
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-575175452525"
  bucket_path: "docker"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
