language: generic
sudo: required
services:
	- docker:

before_install:
    - docker build -t yashchauhan/docker-react -f Dockerfile.dev .

script:
  - docker run yashchauhan/docker-react npm run test -- --coverage
